name: Cron Check

on:
  schedule:
    - cron: "*/2 * * * *"  # every 2 minutes

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the time
        run: echo "Cron ran at $(date)"
