name: 1-Minute Dispatcher

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger visa-check workflow every minute for 15 mins
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Starting 15-minute dispatch loop..."
          for i in {1..15}; do
            echo "Dispatching visa-check iteration $i at $(date)"
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$REPO/actions/workflows/visa-check.yml/dispatches \
              -d '{"ref":"main"}'
            sleep 60
          done
