name: Check Visa Slot Every Minute

on:
  schedule:
    - cron: "* * * * *"  # every minute
  workflow_dispatch:     # allow manual run from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Run Railway command
        run: railway run --project ${{ secrets.RAILWAY_PROJECT }} "python main.py"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
