name: Check Visa Slot Every Minute

on:
  schedule:
    - cron: "* * * * *"  # every minute
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link to Railway project
        run: railway link --project ${{ secrets.RAILWAY_PROJECT }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run Python script on Railway
        run: railway run -- python main.py
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
